### ISSUE TITLE
Import error when running tensorflow with 5/5 path settings

### ISSUE THREAD

**Issue by DavidFowler** [TobyHFerguson/cdsw-demo-short#9]
First couple of errors from running the 3_tensorflow.py (other py ran ok):

Import MNIST data

from tensorflow.examples.tutorials.mnist import input_data
AttributeError: 'module' object has no attribute 'computation'
AttributeErrorTraceback (most recent call last)
in engine
----> 1 from tensorflow.examples.tutorials.mnist import input_data

/home/cdsw/.local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py in <module>()
     19 from __future__ import print_function
     20 
---> 21 from tensorflow.examples.tutorials.mnist import input_data
     22 from tensorflow.examples.tutorials.mnist import mnist

/home/cdsw/.local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py in <module>()
     27 from six.moves import xrange  # pylint: disable=redefined-builtin
     28 import tensorflow as tf
---> 29 from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets

**Comment by TobyHFerguson** [comment]
Known error with tensorflow. Jira DSE-1861 is tracking this
